# Generated by Django 5.1.4 on 2026-07-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('served', 'Served')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('served', 'Served')], default='pending', max_length=12),
        ),
    ]
