# Generated by Django 5.1.4 on 2026-07-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_order_kitchen_status_orderitem_kitchen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comp_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='covers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_complimentary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comp_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_complimentary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine-in'), ('takeaway', 'Pick up'), ('delivery', 'Delivery'), ('qr', 'QR self-order')], default='dine_in', max_length=12),
        ),
    ]
