# Generated by Django 5.1.4 on 2026-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
